### ISSUE TITLE
Can't enter recovery after power off

### ISSUE THREAD

**Issue by sniperle** [danielstuart14/hybrid_caf_bootstacks#1]
On my d802 I'm not able to enter recovery when I press Power + Volume down twice. 
Phone was powered off before. 
With the lg-dev bootstack everything is working as expected.

**Comment by danielstuart14** [comment]
my bootstacks uses the most recent kk aboot (20H).
This aboot has a new way to enter in recovery.
how enter in recovery: power + vol down, then when the screen goes on, vol
up + vol down.

2015-08-16 5:07 GMT-03:00 Doc Sniper <notifications@github.com>:

> On my d802 I'm not able to enter recovery when I press Power + Volume down
> twice.
> Phone was powered off before.
> With the lg-dev bootstack everything is working as expected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielstuart14/hybrid_caf_bootstacks/issues/1>.
>



-- 
daniel p. stuart

**Comment by sniperle** [comment]
Alright, can confirm this is working.

My fault, didn't know that, sorry for opening this issue. ;-)
