### ISSUE TITLE
Can't enter recovery, even with new method

### ISSUE THREAD

**Issue by mrk2005** [danielstuart14/hybrid_caf_bootstacks#2]
I'm on D802.
If I hold power + vol down, and then vol down + vol up, it asks me to erase data. I go ahead, and it reboots telling me
secure booting error!
cause: boot certification verify 
and it shuts down. 
My ROM (Aicp 10) is stuck on logo, and I can't enter recovery. I can't do anything!
Please help!

**Comment by danielstuart14** [comment]
As the warning on xda OP says, you must be using a bumped recovery before
flashing it. Now, the only way is kdz.
Em 03/12/2015 08:32, "mrk2005" <notifications@github.com> escreveu:

**Comment by schlamar** [comment]
I have the same issue entering recovery, but my ROM (CM 12.1) still works. Is there an alternative to going back to stock ROM?

**Comment by danielstuart14** [comment]
You don't need to flash kdz on this case. Just download flashify on google
play and then flash cyanogen recovery image. (You can found it on get.cm )

Em qui, 10 de dez de 2015 06:23, Marc Schlaich <notifications@github.com>
escreveu:

**Comment by lbartik** [comment]
CAF bootstack fixed CM13 and simultaneously broke TWRP.  I figured all hope was lost.  But Flashify worked with the matching CM13 CWM recovery.IMG!  Now I am also able to flash the 30f blastigator boostack and revert back to CM12.1 latest stable release.
