### ISSUE TITLE
LG D803 Modem Crashes

### ISSUE THREAD

**Issue by Jonatino** [danielstuart14/hybrid_caf_bootstacks#3]
I was able to look at the last_kmsg and see that it is due to the modem crashing. 

Here is the full log: 

https://dl.dropboxusercontent.com/u/91292881/ShareX/2016/01/2016-01-30_04-47-14.txt

**Comment by juggie** [comment]
I see the same thing.

**Comment by Jonatino** [comment]
@juggie I committed a fix to the Offical CyanogenMod 6.0.1 build for LG G2 which fixes this issue. https://github.com/CyanogenMod/android_device_lge_g2-common/commit/b081e6bcf90d3772ca78d0cffd42e3768b814c54

**Comment by juggie** [comment]
@Jonatino Awesome, Thanks!  I just updated my rom today actually as it was running a daily about a month old.  I'll report back if the issue occurs again.

**Comment by juggie** [comment]
@Jonatino I saw some crashes today.  I was away from home so I didn't get any kmsg's, but it crashed twice.
